# Generated by Django 5.2.12 on 2026-03-11 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_delete_course_user_is_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
