# Generated by Django 5.2.12 on 2026-03-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('badge', models.CharField(blank=True, help_text='Short label e.g. "New Batch", "Offer"', max_length=40)),
                ('badge_color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange'), ('red', 'Red'), ('purple', 'Purple')], default='blue', max_length=10)),
                ('link', models.URLField(blank=True, help_text='Optional URL the announcement links to')),
                ('link_label', models.CharField(blank=True, default='Learn more', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower = appears first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
